### ISSUE TITLE
k8s redis集群创建失败

### ISSUE THREAD

**Issue by aiadaniel** [mafei198/gos#5]
redis-cluster.yaml脚本并无创建pv的逻辑，是否需要自己创建，能否简单介绍下。

**Comment by aiadaniel** [comment]
no persistent volumes available for this claim and no storage class is set

**Comment by mafei198** [comment]
安装Helm
  brew install kubernetes-helm

部署Redis
  kubectl apply -f k8s/deps/redis/redis-cluster.yaml
  kubectl exec -it redis-cluster-0 -- redis-cli --cluster create --cluster-replicas 1 \
  $(kubectl get pods -l app=redis-cluster -o jsonpath='{range.items[*]}{.status.podIP}:6379 ')

k8s安装说明：dockers/doc/Readme.txt
